const achievementsBD = [
    {
        name: "Windows environment development configuration",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/prework-configuracion-entorno-windows.png",
        image: "../assets/achievements/diploma-configuracion-windows.jpg",
    },
    {
        name: "Introduction to the terminal and command line",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badge-terminal.webp",
        image: "../assets/achievements/diploma-terminal.jpg",
    },
    {
        name: "Professional git and git-hub course",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badge-github.webp",
        image: "../assets/achievements/diploma-git-github.jpg",
    },
    {
        name: "Definitive html and css course",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badges-html-css.webp",
        image: "../assets/achievements/diploma-html-css.jpg",
    },
    {
        name: "Javascript Basic",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badge-basicojs.png",
        image: "../assets/achievements/diploma-basico-javascript.jpg",
    },
    {
        name: "Practical Javascript course",
        title: "Certificate",
        otorgedBy: "platzi",
        logo: "../assets/achievements-icon/practico-javascript_badge.webp",
        image: "../assets/achievements/diploma-javascript-practico.jpg",
    },
    {
        name: "Javascript: basic mathematics and statistics",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/practico-javascript-matematicas_piezas_badge.webp",
        image: "../assets/achievements/diploma-javascript-practico-matematicas.jpg",
    },
    {
        name: "Javascript practical workshop: video-game",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badge-js-videojuegos-web.png",
        image: "../assets/achievements/diploma-javascript-practico-videojuegos.jpg",
    },
    {
        name: "Object-oriented programming",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badges-poo.webp",
        image: "../assets/achievements/diploma-oop.jpg",
    },
    {
        name: "Closure and scope in javascript",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/badge-piezas-clousures-scope-javascript.webp",
        image: "../assets/achievements/diploma-javascript-closures-scope.jpg",
    },
    {
        name: "Introduction to react",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/piezas-reactjs-badge.png",
        image: "../assets/achievements/diploma-react-2021.jpg",
    },
    {
        name: "React.js Course",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/react.png",
        image: "../assets/achievements/diploma-react.jpg",
    },
    {
        name: "React.js: Render and composition patterns",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/reactjs-patrones-render_badge.webp",
        image: "../assets/achievements/diploma-react-patrones-render.jpg",
    },
    {
        name: "React.js: professional state management",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/react-manejo-estado.png",
        image: "../assets/achievements/diploma-react-estado.jpg",
    },
    {
        name: "React.js with Vite.js and Tailwind.css",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/piezas-basico-tailwind_badge.png",
        image: "../assets/achievements/diploma-react-vite-tailwindcss.jpg",
    },
    {
        name: "React.js: E-COMMERSE professional",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/piezas-laboratorio-javascript-fake-store-copy_badge.webp",
        image: "../assets/achievements/diploma-laboratorio-react.jpg",
    },
    {
        name: "Database fundamentals",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/fundamentos-de-bases-de-datos.webp",
        image: "../assets/achievements/diploma-bd.jpg",
    },
    {
        name: "SQL and MySQL course",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/mysql.webp",
        image: "../assets/achievements/diploma-sql-mysql.jpg",
    },
    {
        name: "React.js and Redux professional course",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/icon-redux.png",
        image: "../assets/achievements/diploma-react-redux.jpg"
    },
    {
        name: "React.js Navigation with React-Router",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/icon-react-router.png",
        image: "../assets/achievements/diploma-react-router.jpg"
    },
    {
        name: "State machine with react.js",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/icon-machine-state.png",
        image: "../assets/achievements/diploma-react-state-machines.jpg"
    },
    {
        name: "Basic english course A1: Short a common conversations",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/conversacion.jpg",
        image: "../assets/achievements/diploma-ingles-principiantes.jpg",
    },
    {
        name: "Basic Workshop for personal descriptions",
        title: "Certificate",
        otorgedBy: "Platzi",
        logo: "../assets/achievements-icon/ingles-basico.jpg",
        image: "../assets/achievements/diploma-taller-descripciones-personales.jpg",
    },
];

export {achievementsBD};